version: '3.8'

services:
  api:
    image: munavvarsinan/url-shortener-api:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d url-shortener" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
