version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./.env
        - action: sync
          path: ./src
          target: /usr/src/app/src
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d url-shortener" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
