version: '1.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run dev
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
      - JWT_SECRET=dev-secret-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url-shortener
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url-shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
